---
services:
  redis:
    image: redis
    volumes:
      - /opt/docker/redis/data:/data
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    expose:
      - 6379
